### ISSUE TITLE
Kernel update

### ISSUE THREAD

**Issue by betacentauri** [HD-Digital/meta-gfutures#10]
Kernel update always uses first kernel device:
https://github.com/HD-Digital/meta-gfutures/blob/master/recipes-bsp/linux/linux-hd_4.4.35.bb#L55

You have to write the kernel into currently used kernel device.

**Comment by MarkusVolk** [comment]
a simple hack to create /dev/kernel symlink for the current kernel partition would be:

#!/bin/sh
image=$(sed -e 's/^.*rootsubdir=//' -e 's/ .*$//' < /proc/cmdline | grep -o '[0-9]')
if [ image = "1" ]; then image=""; fi
ln -sf /dev/disk/by-partlabel/linuxkernel$image /dev/kernel

You will probably have to edit /dev/disk/by-partlabel to /dev/block/by-name for e2 images

**Comment by betacentauri** [comment]
Or maybe better use this solution:
https://github.com/oe-alliance/oe-alliance-core/commit/4a9e2635ef127ce95494ba41d4b43464337dddd4

**Comment by HD-Digital** [comment]
Thank you for both solutions and thinking with us for a good solutions. By adding in startup line kernel=/dev/mmcblk0p19 seems to been for now the easist solutions

**Comment by HD-Digital** [comment]
add solution in the bsp-layer for detect /dev/kernel
