### ISSUE TITLE
Rescue boot on hd51 doesn't work anymore

### ISSUE THREAD

**Issue by MarkusVolk** [HD-Digital/meta-gfutures#16]
With the new partition layout my hd51 lost the capability of booting the first kernel by holding the power button pressed at boot.

Probably because the bootloader still tries to find the kernel in emmcflash0.kernel1, while the new naming is emmcflash0.linuxkernel

**Comment by HD-Digital** [comment]
Right, this is changed we will check it out and launch a new bootloader which want to use this option

**Comment by HD-Digital** [comment]
Bootloader which should start slot1 as fail safe:
http://mutant-digital.net/downloads/bootloader/hd51-bolt-v107r27.zip

**Comment by MarkusVolk** [comment]
I can confirm that the bootloader fixes the problem. I had to create the file "imageversion" so that it could be flashed. Thank you
