### ISSUE TITLE
recovery and image structure HD60

### ISSUE THREAD

**Issue by HD-Digital** [HD-Digital/meta-gfutures#7]
HD60

The image structure will make now two files *recovery_emmc.zip and *_emmc.zip
The *_emmc.zip can been used in the future as well for ofgwrite and will now been used by the recovery interface for install the image manual.

The recovery_emmc.zip should been install normally once (or if there is an update.)
This is needed for avoid images conflicts as the partition layout (bootargs) is of huge essential. A small change can destroy all your install images. So we can better leave it and not install it if it's not need.

I hope you can offer one-time the recovery file in your download and the dated builds of the images which has only a kernel and rootfs in tar.bz2 only.
https://github.com/HD-Digital/meta-gfutures/tree/release-7.x

Unfortunally image install should been done only by the recovery menu. I hope the users will see the importants of it and accept this new way of update.

**Comment by WanWizard** [comment]
Just seen this.

Done all that, and the reception from endusers is very mixed, to say it mildly...
